language: scala
scala:
  - 2.11.11
  - 2.12.2
jdk:
  - oraclejdk8
# See https://github.com/scala-js/scala-js/issues/2642
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom
